### ISSUE TITLE
Must rename extensions for use in workes to js (.cjs does not work)

### ISSUE THREAD

**Issue by LaurentDhont** [juanelas/paillier-bigint#11]
TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be ".js" or ".mjs". Received ".cjs"

Just rename the files and it will work.

**Comment by RaulBejarano** [comment]
Hello, I'm getting the same error and I don't know how to solve it.

**Comment by juanelas** [comment]
Are you using node version 10? Updating to a more recent version (node 10 is no longer supported) should fix the issue. If that is not the case, I would need more details about how to reproduce the issue.

**Comment by juanelas** [comment]
Since I cannot reproduce the issue, I (temporarily) close it.
