### ISSUE TITLE
Missing addition of ciphertext with plaintext

### ISSUE THREAD

**Issue by gitcnd** [juanelas/paillier-bigint#12]
Author forgot to include the one-liner for adding non-encrypted values to ciphertext...

Something like this:-

`encryptedSum = c1 * (g**5n) % (n*n); // Add 5 to ciphertext c1`

**Comment by juanelas** [comment]
You are right. That functionality has been missing. Thank you @gitcnd for pointing that out! It's been added to the last version (v3.3.0)
