### ISSUE TITLE
Is there any way to check number is positive?

### ISSUE THREAD

**Issue by KaffinPX** [juanelas/paillier-bigint#13]

**Comment by juanelas** [comment]
To the best of my knowledge, there is not. This would leak information regarding the ciphertext that could be used to "decrypt" it just subtracting numbers until it is negative.

**Comment by KaffinPX** [comment]
Do you know any algorithm like that?

**Comment by juanelas** [comment]
Something like the following will decrypt `ciphertext` and let the result in `decrypted` with just knowledge of the public key `pubKey`. Obviously you would need a function `isPositive` allowing you to check if the ciphertext is positive...

```javascript
const encryptedMinusOne = pubKey.encrypt(-1n)
let decrypted = 0
do {
   ciphertext = pubKey.addition(ciphertext, encryptedMinusOne)
   decrypted++
} while (isPositive(ciphertext)
```
