### ISSUE TITLE
Error with React Native 

### ISSUE THREAD

**Issue by harrycheng20** [juanelas/paillier-bigint#3]
# Description 
I am trying to import this module into a new react-native project and got this error: `No identifiers allowed directly after numeric literal`, for your information I put the content of `App.js` here:

```
import React from 'react';
import {Text, View} from 'react-native';
import * as paillier from 'paillier-bigint';

function HelloWorldApp() {
  return (
    <View
      style={{ flex: 1,
        justifyContent: 'center',
        alignItems: 'center'
      }}>
      <Text>Hello, world!</Text>
    </View>
  )
}


export default HelloWorldApp;
```
I think this error is caused by the dependency `bigint-crypto-utils` because when I tried to import `bigint-crypto-utils` it gave me the same error. 

# System Information: 
```
OS: Ubuntu 18.04.4 LTS
node version: v14.0.0
react: 16.11.0
react-native: 0.62.2

```

**Comment by juanelas** [comment]
I haven't tested it with React Native but it is probably failing because of lack of BigInt support, which is ES11 (ES2020), in the default setup. You may try to change target and lib to 'es2020' or 'esnext', although I'm really not sure if it will cause runtime errors. Please let me know if it works. As soon as I find time, I will try it myself but I don't see it coming in less than a month or so.
Thank you for contributing!

**Comment by harrycheng20** [comment]
Hi Juan, thanks for replying. I don't know how to change target and lib to 'es2020' or 'esnext', but I tried your [paillier-js](https://github.com/juanelas/paillier-js) repository which relies on [big-integer](https://www.npmjs.com/package/big-integer), and it does works in react native. One problem with big-integer is that the computation is quite slow,  one encryption operation using a 2048-bit public key takes about 1 minute on an Android emulator.  If I rewrite the big-integer operation in Java and use it in react native, the encryption operation takes less than 1 second.

**Comment by juanelas** [comment]
Great to know! In any case I abandoned paillier-js long ago in favour of paillier-bigint long ago, so if you need a reference implementation I rather user the latter one.
Thank you for the feedback!
